# Generated by Django 3.1.3 on 2020-11-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0004_delete_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
    ]
