# Generated by Django 3.1.3 on 2020-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0005_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_before',
            field=models.FloatField(default=0),
        ),
    ]
