# Generated by Django 3.1.3 on 2020-11-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
