# Generated by Django 3.1.3 on 2020-11-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(default='Guna', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='landmark',
            field=models.CharField(default='jaypee university', max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=1234567890, max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='pincode',
            field=models.IntegerField(default=473226),
        ),
    ]
